/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.bit.felinae;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        WebService web = new WebService();
        try {
            web.startServer();
        }catch (Exception e){

        }
    }
}
